<div class="fs-block">
    <img style="width: 12em" src="https://upload.wikimedia.org/wikipedia/commons/8/89/Fiserv_logo.svg">
    <div style="margin-top: 1em;margin-bottom: 1em">
        <?= $escaper->escapeHtml(__('Pay securely with Fiserv Checkout. Acquire API credentials on our developer portal.')) ?>
    </div>
    <a href="https://docs.fiserv.dev/public/docs/guides">
        <?= $escaper->escapeHtml(__('Visit Fiserv developer guide')) ?>
    </a>
</div>