<div class="fs-block">
    <img style="width: 12em" src="https://upload.wikimedia.org/wikipedia/commons/8/89/Fiserv_logo.svg">
    <div style="margin-top: 1em;margin-bottom: 1em">
        <?= $block->escapeHtml(__('Sicheres Bezahlen mit Fiserv Checkout. Erwerben Sie API-Zugangsdaten auf unserem Entwicklerportal')) ?>
    </div>
    <?= $block->escapeHtml(__('Besuchen Sie developer.fiserv.com')) ?>
</div>