<div class="mm-block-ginger">
    <a class="helpbutton" target="_blank"></a>
    <p>
        <?= $block->escapeHtml(__('Pay securely with Fiserv')) ?>
    </p>
    <table>
        <tbody>
            <tr>
                <td>
                    <div class="icon1"></div>
                    <?= $block->escapeHtml(__('Visit developer.fiserv.com')) ?>
                </td>
            </tr>
        </tbody>
    </table>
</div>