<tr id=<?= 'row_' . $element->getHtmlId() ?>>
    <td class="label"></td>
    <td class="value">
        <div class="mm-heading-ginger">
            <?= $escaper->escapeHtml(__($element->getData('label'))) ?>
        </div>
        <div class="mm-comment-ginger">
            <div id="content">
                <?= $escaper->escapeHtml(__($element->getData('comment'))) ?>
            </div>
        </div>
    </td>
    <td></td>
</tr>